name: Create a Release

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "*.*.*"
  # push:
  #   branches:
  #     - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # - name: Download and extract compiled script
      #   run: |
      #     wget https://github.com/lumenwrites/process-course/releases/download/v1.0.0/process-course-linux -O process-course # replace with the URL of your compiled script

      #     chmod +x process-course

      - name: Clone script repository
        run: git clone https://github.com/lumenwrites/process-course

      - name: Install dependencies and build the script
        working-directory: process-course
        run: |
          npm ci

      - name: Run compiled script
        run: |
          npm run start
